/control/verbose 0
/geometry/source data/brain/brain.tg
/score/create/boxMesh prionScorer
/score/mesh/boxSize 5 5 5 cm
/score/mesh/nBin 50 50 50
/score/quantity/energyDeposit eDep
/score/close
/run/initialize

# Gamma -- 5000 particles
/gps/particle gamma
/gps/energy 1.17 MeV
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 15 mm
/gps/pos/centre 0 0 0 mm
/run/beamOn 5000

# Neutron -- 5000 particles
/gps/particle neutron
/gps/energy 2.0 MeV
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 15 mm
/gps/pos/centre 0 0 0 mm
/run/beamOn 5000

# Carbon Ion -- 1000 particles
/gps/particle ion
/gps/ion 6 12
/gps/energy 3960 MeV
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 15 mm
/gps/pos/centre 0 0 0 mm
/run/beamOn 1000

# Alpha -- 5000 particles
/gps/particle alpha
/gps/energy 5.5 MeV
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 15 mm
/gps/pos/centre 0 0 0 mm
/run/beamOn 5000

/score/dumpQuantityToFile prionScorer eDep opt_current_5_5_1_5.csv