/geometry/source /Users/penguin/Desktop/prion_radiation_research/surgical_tool/structure/surgical_tool.tg

/score/create cubicMesh prionMesh
/score/mesh/boxSize 5 5 50 mm
/score/mesh/nBin 10 10 100
/score/quantity/energyDeposit eDep
/score/close

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 -60 mm
/gps/pos/halfx 4 mm
/gps/pos/halfy 4 mm
/gps/direction 0 0 1
/gps/ene/mono 6 MeV
/run/beamOn 2000

/score/dumpQuantityToFile prionMesh eDep gamma_edep.csv
