/control/verbose 1
/geometry/source structure/surgical_tool.tg

/score/create/boxMesh rodMesh
/score/mesh/boxSize 5 5 50 mm
/score/mesh/nBin 10 10 100
/score/quantity/energyDeposit eDep
/score/close
/run/initialize

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 -49 mm
/gps/pos/halfx 4 mm
/gps/pos/halfy 4 mm
/gps/direction 0 0 1
/gps/ene/mono 6 MeV
/run/beamOn 2000

/score/dumpQuantityToFile rodMesh eDep gamma_edep.csv
